version: "3.9"
services:
  postgres:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=go_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/go_bank?sslmode=disable
    entrypoint: [ "/app/wait-for.sh" , "postgres:5432" , "--" , "/app/start.sh" ]
    command: ["/app/main"]